// export const subSections = {
//   Tech: {
//     Apple: ["iPhone", "MacBook", "iPad"],
//     Audio: ["Headphones", "Speakers", "Earbuds"],
//     Cameras: ["DSLR", "Mirrorless", "Action-Cameras"],
//     Computers: ["Laptops", "Desktops", "Tablets"],
//     Smartphones: ["Android", "iOS", "Windows-Phone"],
//     TVs: ["LG", "Samsung", "Sony", "Projectors"],
//   },
//   Fashion: {
//     "Men's-Fashion-Advice": ["Formal", "Casual", "Business-Casual"],
//     "Men's-Fashion-Trends": ["Seasonal-Trends", "Streetwear", "Minimalist"],
//     "Men's-Fragrances": ["Cologne", "Perfume", "Body-Spray"],
//     "Men's-Hairstyles": ["Short", "Medium", "Long"],
//     "Sneakers-&-Shoes": ["Sneakers", "Dress-Shoes", "Boots"],
//     Watches: ["Analog", "Digital", "Smartwatches"],
//   },
//   Rides: {
//     Boats: ["Yachts", "Superyachts", "Sailing", "Jetskis", "Submarines"],
//     Cars: [
//       "Most-Popular-Car-Brands",
//       "Electric-Vehicles",
//       "SUVs",
//       "Porsche",
//       "Ford",
//       "BMW",
//       "Sports-Cars",
//       "Mercedes-Benz",
//       "Luxury",
//       "Reviews",
//     ],
//     Cycling: [
//       "Bicycles",
//       "Electric-Bikes",
//       "Helmets",
//       "Mountain-Bikes",
//       "Kickstarter",
//       "Buyers-Guides",
//       "Best-Electric-Bikes",
//     ],
//     Flying: [
//       "Planes",
//       "Jets",
//       "Electric-Vehicles",
//       "Space",
//       "Travel",
//       "Auctions",
//     ],
//     Motorcycles: [
//       "Best-Cafe-Racers",
//       "Fastest-Motorcycles-in-the-World",
//       "Electric-Motorcycles",
//       "Harley-Davidson",
//       "Cafe-Racers",
//       "Triumph",
//       "Vintage-Helmets",
//       "Motorcycle-Backpacks",
//     ],
//   },
//   Lifestyle: {
//     Advice: [
//       "Health",
//       "Mental-Health",
//       "COVID-19",
//       "Money",
//       "Australia",
//       "Work",
//       "Productivity",
//       "Investing",
//       "Cryptocurrency",
//     ],
//     Drinks: ["Whisky", "Beer", "Wine", "Cocktails", "Bars"],
//     Fitness: [
//       "Workouts",
//       "Shoulder-Exercises",
//       "Bicep-Exercises",
//       "Triceps-Workouts",
//       "Chest-Workouts",
//       "Forearm-Workouts",
//       "Strongest-Celebrities-in-Hollywood",
//       "How-to-Lose-Weight-Fast",
//       "Celebrity-Diet-&-Workout-Plans",
//       "Gyms",
//       "Diet-&-Nutrition",
//     ],
//     Finance: [
//       "Money",
//       "Cryptocurrency",
//       "Investing",
//       "NFTs",
//       "Australia",
//       "Celebrities",
//       "Elon-Musk",
//       "Net-Worths",
//       "Rich-Lists",
//     ],
//     Food: [
//       "Monday-Munchies",
//       "Restaurants",
//       "Fast-Food",
//       "Sydney",
//       "Melbourne",
//       "Brisbane",
//     ],
//     Grooming: [
//       "Skincare",
//       "Razors",
//       "Hair",
//       "Beards",
//       "Best-Beard-Oils",
//       "Best-Body-Groomers",
//       "Best-Face-Washes",
//       "Men's-Skincare-Guide",
//       "Best-Skincare-Products",
//       "Beard-Care-Guide",
//     ],
//     "Sex-&-Dating": [
//       "Best-Sex-Toys",
//       "Best-Tinder-Bios-for-Guys",
//       "How-To-Be-Sexually-Dominant",
//       "A-Guide-to-(Safe)-Rough-Sex",
//       "How-to-Get-a-Sugar-Momma",
//       "Tinder-Pick-Up-Lines-for-Guys",
//       "Best-Sex-Positions",
//       "Best-Dating-Apps",
//     ],
//     Travel: [
//       "Hotels",
//       "Sydney",
//       "Melbourne",
//       "Best-Hotels-in-the-World",
//       "Travel-Gifts",
//       "World's-Best-Rooftop-Bars",
//       "Skyscanner-Alternatives",
//       "Qantas",
//     ],
//   },
//   Entertainment: {
//     Art: ["NFTs", "Auctions", "Tattoos", "Collections", "Memes"],
//     Books: [
//       "Coffee-Table-Books",
//       "Self-Help-Books",
//       "Cookbooks",
//       "Best-Kindles",
//     ],
//     Gaming: [
//       "Top-New-Games",
//       "Playstation",
//       "Xbox",
//       "PC",
//       "Nintendo-Switch",
//       "LEGO",
//       "Sony",
//       "Reviews",
//     ],
//     "Movies-&-TV": [
//       "Guide-to-Streaming-Services",
//       "New-on-Netflix",
//       "New-on-Prime-Video",
//       "New-on-Disney+",
//       "New-on-Stan-Australia",
//       "Best-Action-Movies",
//       "Best-Sci-Fi-Movies",
//       "Trailers",
//       "Netflix",
//       "Best-Movies-on-Netflix",
//       "Best-Amazon-Prime-Movies",
//       "Best-Shows-on-Netflix",
//       "Documentaries",
//       "James-Bond",
//     ],
//     Music: ["Guitars", "Festivals", "Hip-Hop"],
//     Sport: [
//       "Golf",
//       "NBA",
//       "Football",
//       "Boxing",
//       "Tennis",
//       "UFC",
//       "AFL",
//       "Formula-1",
//     ],
//   },
//   Living: {
//     Appliances: [
//       "Vacuum-Cleaners",
//       "Coffee",
//       "Kitchens",
//       "Cooking",
//       "Lighting",
//       "Dyson",
//       "Best-Coffee-Machines",
//       "Best-Air-Fryers",
//       "Best-Robot-Vacuums",
//     ],
//     Architecture: [
//       "Homes",
//       "Design",
//       "Real-Estate",
//       "Interior-Design",
//       "Penthouses",
//       "Celebrity-Homes",
//     ],
//     Furniture: [
//       "Desks",
//       "IKEA",
//       "Interior-Design",
//       "Homes",
//       "Italian",
//       "Chairs",
//       "Office",
//       "Tables",
//       "Design",
//       "Herman-Miller",
//     ],
//     Homewares: [
//       "Decor",
//       "Kitchenware",
//       "Bedding",
//       "Lighting",
//       "Storage",
//       "Candles",
//       "Plants",
//       "Art",
//     ],
//   },
//   Outdoors: {
//     Camping: [
//       "Tents",
//       "Campervans",
//       "Knives",
//       "Vehicles",
//       "Australia",
//       "4WD",
//       "Fishing",
//       "Kayaks",
//       "Kickstarter",
//     ],
//     Snow: [
//       "Skiing",
//       "Snowboarding",
//       "Cabins",
//       "Best-Ski-Jackets",
//       "Best-Snow-Goggles",
//       "Best-Ski-Fields-in-New-Zealand",
//       "Winter-Must-Haves",
//       "Best-Australian-Ski-Fields",
//     ],
//     Surfing: [
//       "Beaches",
//       "Wetsuits",
//       "Surfboards",
//       "Best-Wetsuit-Tops",
//       "Best-Wetsuits-for-Surfing",
//     ],
//     Skate: [
//       "Skateboards",
//       "Longboards",
//       "Protective-Gear",
//       "Skate-Shoes",
//       "Street-Skating",
//     ],
//     Hiking: [
//       "Trails",
//       "Gear",
//       "Footwear",
//       "Backpacks",
//       "Clothing",
//       "Best-Hiking-Trails",
//       "Camping",
//     ],
//   },
//   News: {
//     "World-News": ["Politics", "Economy", "Global-Events", "Climate-Change"],
//     "Tech-News": ["AI", "Gadgets", "Startups", "Innovations"],
//     "Sports-News": ["Football", "Basketball", "Olympics", "Cricket"],
//     "Entertainment-News": ["Movies", "Music", "Celebrities", "TV-Shows"],
//   },
// };

export const subSections = {
  Beauty: {
    Nails: [
      "Spring-Nails-2025",
      "French-Tip-Nails",
      "Almond-Nails",
      "Acrylic-Nails",
      "Pink-Nails",
      "Yellow-Nails",
      "Chrome-Nails",
      "Pastel-Nails",
      "Fall-Nails",
      "Christmas-Nails",
      "Easter-Nail-Ideas",
      "Prom-Nails",
      "Graduation-Nails",
      "Summer-Nail-Ideas",
      "Autumn-Nails",
    ],
    Makeup: [
      "Prom-Makeup",
      "Coachella-Makeup",
      "Makeup-Tutorials",
      "Beauty-Bloggers",
      "Makeup-Product-Reviews",
    ],
    Hair: [
      "Hairstyles",
      "Prom-Hairstyles",
      "Curly-Hairstyles",
      "Braided-Hairstyles",
      "Short-Hair-Inspo",
      "Winter-Hair-Braid",
      "Wedding-Hairstyles",
      "Softball-Hairstyles",
      "Track-Hairstyles",
      "Short-Dread-Styles",
    ],
    Skincare: [
      "Skincare-Routines",
      "Product-Reviews",
      "DIY-Skincare",
      "Seasonal-Skincare-Tips",
    ],
  },
  Fashion: {
    Outfits: [
      "Spring-Outfits",
      "Fall-Outfits",
      "Winter-Fashion-Inspo",
      "Summer-Wallpaper",
      "Really-Cute-Outfits",
      "Modest-Summer-Fits",
      "After-Prom-Outfit",
      "Baseball-Game-Outfit",
      "Shorts-Outfits",
    ],
    Dresses: [
      "Prom-Dresses",
      "Wedding-Dresses",
      "Graduation-Dress",
      "Dress-to-Impress",
    ],
    Accessories: ["Cool-Sunglasses", "Earrings-Trends", "Your-It-Bag", "Shoes"],
    Trends: [
      "Fashion-Bloggers",
      "Seasonal-Trends",
      "Streetwear",
      "Minimalist-Fashion",
    ],
  },
  Lifestyle: {
    Food: [
      "Dinner-Ideas",
      "Easy-Dinner-Recipes",
      "Healthy-Dinner-Recipes",
      "Chicken-Recipes",
      "Ground-Beef-Recipes",
      "Crockpot-Recipes",
      "Breakfast-Ideas",
      "Banana-Bread-Recipe",
      "Pasta-Salad",
      "French-Toast-Casserole",
      "Side-Dishes-for-Ham",
      "Ham-Side-Dishes",
    ],
    Home: [
      "Home-Aesthetic-DIY",
      "Bedroom-Ideas",
      "Home-Bedroom-Refresh",
      "Spring-Tablescapes",
      "Earth-Day-Crafts",
      "Earth-Day-Art",
      "Earth-Day-Crafts-for-Preschoolers",
    ],
    Events: [
      "Future-Wedding-Plans",
      "Promposal-Ideas",
      "Prom-Bouquet",
      "Prom-Poses",
      "Individual-Prom-Poses",
      "Senior-Prom-Captions-for-Instagram",
      "Senior-Night-Poster",
      "Senior-Baskets-Gift-Ideas",
      "Mother's-Day-Gifts",
      "Mother's-Day-Crafts-for-Kids",
      "Mother's-Day-Photoshoot",
      "Mother's-Day-Ideas",
      "Teacher-Appreciation-Gifts",
      "Teacher-Appreciation-Door-Decorations",
      "Administrative-Professionals-Day-Gifts",
    ],
    Inspiration: [
      "Small-Tattoo-Inspo",
      "Drawing-Ideas",
      "Lyrics",
      "Aesthetic",
      "Color",
      "Hello-Kitty",
      "Easter-Chalkboard-Art",
    ],
  },
  Travel: {
    Destinations: [
      "Winter-Travel-Inspo",
      "Coachella",
      "Strawberry-Festival-Outfits",
    ],
    Planning: ["Date-Planning-Inspo", "Shop-Party-Pieces"],
  },
  Media: {
    Platforms: ["YouTube", "Pinterest", "Instagram"],
    Content: [
      "Beauty-Bloggers",
      "Fashion-Bloggers",
      "Lifestyle-Bloggers",
      "Makeup-Tutorials",
    ],
  },
  Wellness: {
    Fitness: ["Workout-Routines", "Healthy-Living-Tips"],
    "Mental-Health": ["Self-Care-Ideas", "Mindfulness-Practices"],
  },
  CollegeLife: {
    Dorm: [
      "Dorm-Room-Decor",
      "College-Room-Ideas",
      "Dorm-Organization-Hacks",
      "Dorm-Desk-Setup",
      "Dorm-Aesthetic-Posters",
    ],
    School: [
      "Back-To-School-Outfits",
      "Cute-School-Supplies",
      "Note-Taking-Hacks",
      "Study-Tips",
      "First-Day-Of-School-Captions",
    ],
    College: [
      "College-Packing-List",
      "College-Dorm-Essentials",
      "College-Morning-Routine",
      "What’s-In-My-Backpack",
      "Finals-Week-Survival-Guide",
    ],
  },
  SeasonalFun: {
    Spring: [
      "Spring-Bucket-List",
      "Spring-Crafts-for-Kids",
      "Easter-Table-Decor",
      "Spring-Outdoor-Activities",
      "Spring-Cleaning-Checklist",
    ],
    Summer: [
      "Summer-Bucket-List",
      "Summer-Party-Ideas",
      "Summer-Vibes-Aesthetic",
      "DIY-Pool-Party-Decor",
      "Fourth-of-July-Ideas",
    ],
    Fall: [
      "Fall-Bucket-List",
      "Pumpkin-Carving-Ideas",
      "Halloween-Costumes-for-Best-Friends",
      "Thanksgiving-Table-Decor",
      "Fall-Family-Photoshoot-Ideas",
    ],
    Winter: [
      "Winter-Bucket-List",
      "Christmas-Crafts",
      "New-Year’s-Party-Decor",
      "Hot-Chocolate-Bar-Setup",
      "DIY-Gift-Ideas",
    ],
  },
};
